/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTaskGraphRouteImport } from './routes/_authenticated/task-graph'
import { Route as AuthenticatedSimpleCacheTestRouteImport } from './routes/_authenticated/simple-cache-test'
import { Route as AuthenticatedSendNoticeRouteImport } from './routes/_authenticated/send-notice'
import { Route as AuthenticatedProjectOverviewRouteImport } from './routes/_authenticated/project-overview'
import { Route as AuthenticatedMyTasksRouteImport } from './routes/_authenticated/my-tasks'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated/kanban'
import { Route as AuthenticatedGanttNewRouteImport } from './routes/_authenticated/gantt-new'
import { Route as AuthenticatedGanttRouteImport } from './routes/_authenticated/gantt'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages/index'
import { Route as AuthenticatedDocumentsIndexRouteImport } from './routes/_authenticated/documents/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedTemplatesSelectRouteImport } from './routes/_authenticated/templates/select'
import { Route as AuthenticatedTemplatesManagementRouteImport } from './routes/_authenticated/templates/management'
import { Route as AuthenticatedTasksCreateRouteImport } from './routes/_authenticated/tasks/create'
import { Route as AuthenticatedTasksTaskIdRouteImport } from './routes/_authenticated/tasks/$taskId'
import { Route as AuthenticatedStatusManagerRouteImport } from './routes/_authenticated/status/manager'
import { Route as AuthenticatedSettingsPasswordRouteImport } from './routes/_authenticated/settings/password'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as AuthenticatedInstanceCreateRouteImport } from './routes/_authenticated/instance/create'
import { Route as AuthenticatedDocumentsCreateRouteImport } from './routes/_authenticated/documents/create'
import { Route as AuthenticatedDocumentsDocumentIdRouteImport } from './routes/_authenticated/documents/$documentId'
import { Route as AuthenticatedTemplatesDetailTaskTypeIdRouteImport } from './routes/_authenticated/templates/detail/$taskTypeId'
import { Route as AuthenticatedDocumentsEditDocumentIdRouteImport } from './routes/_authenticated/documents/edit.$documentId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTaskGraphRoute = AuthenticatedTaskGraphRouteImport.update({
  id: '/task-graph',
  path: '/task-graph',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSimpleCacheTestRoute =
  AuthenticatedSimpleCacheTestRouteImport.update({
    id: '/simple-cache-test',
    path: '/simple-cache-test',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSendNoticeRoute = AuthenticatedSendNoticeRouteImport.update({
  id: '/send-notice',
  path: '/send-notice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectOverviewRoute =
  AuthenticatedProjectOverviewRouteImport.update({
    id: '/project-overview',
    path: '/project-overview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyTasksRoute = AuthenticatedMyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGanttNewRoute = AuthenticatedGanttNewRouteImport.update({
  id: '/gantt-new',
  path: '/gantt-new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGanttRoute = AuthenticatedGanttRouteImport.update({
  id: '/gantt',
  path: '/gantt',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsIndexRoute =
  AuthenticatedDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesSelectRoute =
  AuthenticatedTemplatesSelectRouteImport.update({
    id: '/templates/select',
    path: '/templates/select',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesManagementRoute =
  AuthenticatedTemplatesManagementRouteImport.update({
    id: '/templates/management',
    path: '/templates/management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksCreateRoute =
  AuthenticatedTasksCreateRouteImport.update({
    id: '/tasks/create',
    path: '/tasks/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksTaskIdRoute =
  AuthenticatedTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatusManagerRoute =
  AuthenticatedStatusManagerRouteImport.update({
    id: '/status/manager',
    path: '/status/manager',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsPasswordRoute =
  AuthenticatedSettingsPasswordRouteImport.update({
    id: '/password',
    path: '/password',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstanceCreateRoute =
  AuthenticatedInstanceCreateRouteImport.update({
    id: '/instance/create',
    path: '/instance/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsCreateRoute =
  AuthenticatedDocumentsCreateRouteImport.update({
    id: '/documents/create',
    path: '/documents/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsDocumentIdRoute =
  AuthenticatedDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesDetailTaskTypeIdRoute =
  AuthenticatedTemplatesDetailTaskTypeIdRouteImport.update({
    id: '/templates/detail/$taskTypeId',
    path: '/templates/detail/$taskTypeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsEditDocumentIdRoute =
  AuthenticatedDocumentsEditDocumentIdRouteImport.update({
    id: '/documents/edit/$documentId',
    path: '/documents/edit/$documentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/gantt': typeof AuthenticatedGanttRoute
  '/gantt-new': typeof AuthenticatedGanttNewRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/my-tasks': typeof AuthenticatedMyTasksRoute
  '/project-overview': typeof AuthenticatedProjectOverviewRoute
  '/send-notice': typeof AuthenticatedSendNoticeRoute
  '/simple-cache-test': typeof AuthenticatedSimpleCacheTestRoute
  '/task-graph': typeof AuthenticatedTaskGraphRoute
  '/': typeof AuthenticatedIndexRoute
  '/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdRoute
  '/documents/create': typeof AuthenticatedDocumentsCreateRoute
  '/instance/create': typeof AuthenticatedInstanceCreateRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/password': typeof AuthenticatedSettingsPasswordRoute
  '/status/manager': typeof AuthenticatedStatusManagerRoute
  '/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute
  '/tasks/create': typeof AuthenticatedTasksCreateRoute
  '/templates/management': typeof AuthenticatedTemplatesManagementRoute
  '/templates/select': typeof AuthenticatedTemplatesSelectRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/documents/edit/$documentId': typeof AuthenticatedDocumentsEditDocumentIdRoute
  '/templates/detail/$taskTypeId': typeof AuthenticatedTemplatesDetailTaskTypeIdRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/gantt': typeof AuthenticatedGanttRoute
  '/gantt-new': typeof AuthenticatedGanttNewRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/my-tasks': typeof AuthenticatedMyTasksRoute
  '/project-overview': typeof AuthenticatedProjectOverviewRoute
  '/send-notice': typeof AuthenticatedSendNoticeRoute
  '/simple-cache-test': typeof AuthenticatedSimpleCacheTestRoute
  '/task-graph': typeof AuthenticatedTaskGraphRoute
  '/': typeof AuthenticatedIndexRoute
  '/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdRoute
  '/documents/create': typeof AuthenticatedDocumentsCreateRoute
  '/instance/create': typeof AuthenticatedInstanceCreateRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/password': typeof AuthenticatedSettingsPasswordRoute
  '/status/manager': typeof AuthenticatedStatusManagerRoute
  '/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute
  '/tasks/create': typeof AuthenticatedTasksCreateRoute
  '/templates/management': typeof AuthenticatedTemplatesManagementRoute
  '/templates/select': typeof AuthenticatedTemplatesSelectRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/documents/edit/$documentId': typeof AuthenticatedDocumentsEditDocumentIdRoute
  '/templates/detail/$taskTypeId': typeof AuthenticatedTemplatesDetailTaskTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/gantt': typeof AuthenticatedGanttRoute
  '/_authenticated/gantt-new': typeof AuthenticatedGanttNewRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/my-tasks': typeof AuthenticatedMyTasksRoute
  '/_authenticated/project-overview': typeof AuthenticatedProjectOverviewRoute
  '/_authenticated/send-notice': typeof AuthenticatedSendNoticeRoute
  '/_authenticated/simple-cache-test': typeof AuthenticatedSimpleCacheTestRoute
  '/_authenticated/task-graph': typeof AuthenticatedTaskGraphRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdRoute
  '/_authenticated/documents/create': typeof AuthenticatedDocumentsCreateRoute
  '/_authenticated/instance/create': typeof AuthenticatedInstanceCreateRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/password': typeof AuthenticatedSettingsPasswordRoute
  '/_authenticated/status/manager': typeof AuthenticatedStatusManagerRoute
  '/_authenticated/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute
  '/_authenticated/tasks/create': typeof AuthenticatedTasksCreateRoute
  '/_authenticated/templates/management': typeof AuthenticatedTemplatesManagementRoute
  '/_authenticated/templates/select': typeof AuthenticatedTemplatesSelectRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/documents/edit/$documentId': typeof AuthenticatedDocumentsEditDocumentIdRoute
  '/_authenticated/templates/detail/$taskTypeId': typeof AuthenticatedTemplatesDetailTaskTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/gantt'
    | '/gantt-new'
    | '/kanban'
    | '/my-tasks'
    | '/project-overview'
    | '/send-notice'
    | '/simple-cache-test'
    | '/task-graph'
    | '/'
    | '/documents/$documentId'
    | '/documents/create'
    | '/instance/create'
    | '/projects/$projectId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/settings/password'
    | '/status/manager'
    | '/tasks/$taskId'
    | '/tasks/create'
    | '/templates/management'
    | '/templates/select'
    | '/chats'
    | '/documents'
    | '/messages'
    | '/projects'
    | '/settings/'
    | '/tasks'
    | '/users'
    | '/documents/edit/$documentId'
    | '/templates/detail/$taskTypeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/gantt'
    | '/gantt-new'
    | '/kanban'
    | '/my-tasks'
    | '/project-overview'
    | '/send-notice'
    | '/simple-cache-test'
    | '/task-graph'
    | '/'
    | '/documents/$documentId'
    | '/documents/create'
    | '/instance/create'
    | '/projects/$projectId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/settings/password'
    | '/status/manager'
    | '/tasks/$taskId'
    | '/tasks/create'
    | '/templates/management'
    | '/templates/select'
    | '/chats'
    | '/documents'
    | '/messages'
    | '/projects'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/documents/edit/$documentId'
    | '/templates/detail/$taskTypeId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/gantt'
    | '/_authenticated/gantt-new'
    | '/_authenticated/kanban'
    | '/_authenticated/my-tasks'
    | '/_authenticated/project-overview'
    | '/_authenticated/send-notice'
    | '/_authenticated/simple-cache-test'
    | '/_authenticated/task-graph'
    | '/_authenticated/'
    | '/_authenticated/documents/$documentId'
    | '/_authenticated/documents/create'
    | '/_authenticated/instance/create'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/password'
    | '/_authenticated/status/manager'
    | '/_authenticated/tasks/$taskId'
    | '/_authenticated/tasks/create'
    | '/_authenticated/templates/management'
    | '/_authenticated/templates/select'
    | '/_authenticated/chats/'
    | '/_authenticated/documents/'
    | '/_authenticated/messages/'
    | '/_authenticated/projects/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/documents/edit/$documentId'
    | '/_authenticated/templates/detail/$taskTypeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/task-graph': {
      id: '/_authenticated/task-graph'
      path: '/task-graph'
      fullPath: '/task-graph'
      preLoaderRoute: typeof AuthenticatedTaskGraphRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simple-cache-test': {
      id: '/_authenticated/simple-cache-test'
      path: '/simple-cache-test'
      fullPath: '/simple-cache-test'
      preLoaderRoute: typeof AuthenticatedSimpleCacheTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/send-notice': {
      id: '/_authenticated/send-notice'
      path: '/send-notice'
      fullPath: '/send-notice'
      preLoaderRoute: typeof AuthenticatedSendNoticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/project-overview': {
      id: '/_authenticated/project-overview'
      path: '/project-overview'
      fullPath: '/project-overview'
      preLoaderRoute: typeof AuthenticatedProjectOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-tasks': {
      id: '/_authenticated/my-tasks'
      path: '/my-tasks'
      fullPath: '/my-tasks'
      preLoaderRoute: typeof AuthenticatedMyTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gantt-new': {
      id: '/_authenticated/gantt-new'
      path: '/gantt-new'
      fullPath: '/gantt-new'
      preLoaderRoute: typeof AuthenticatedGanttNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gantt': {
      id: '/_authenticated/gantt'
      path: '/gantt'
      fullPath: '/gantt'
      preLoaderRoute: typeof AuthenticatedGanttRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/': {
      id: '/_authenticated/documents/'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/select': {
      id: '/_authenticated/templates/select'
      path: '/templates/select'
      fullPath: '/templates/select'
      preLoaderRoute: typeof AuthenticatedTemplatesSelectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/management': {
      id: '/_authenticated/templates/management'
      path: '/templates/management'
      fullPath: '/templates/management'
      preLoaderRoute: typeof AuthenticatedTemplatesManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/create': {
      id: '/_authenticated/tasks/create'
      path: '/tasks/create'
      fullPath: '/tasks/create'
      preLoaderRoute: typeof AuthenticatedTasksCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/$taskId': {
      id: '/_authenticated/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/status/manager': {
      id: '/_authenticated/status/manager'
      path: '/status/manager'
      fullPath: '/status/manager'
      preLoaderRoute: typeof AuthenticatedStatusManagerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/password': {
      id: '/_authenticated/settings/password'
      path: '/password'
      fullPath: '/settings/password'
      preLoaderRoute: typeof AuthenticatedSettingsPasswordRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instance/create': {
      id: '/_authenticated/instance/create'
      path: '/instance/create'
      fullPath: '/instance/create'
      preLoaderRoute: typeof AuthenticatedInstanceCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/create': {
      id: '/_authenticated/documents/create'
      path: '/documents/create'
      fullPath: '/documents/create'
      preLoaderRoute: typeof AuthenticatedDocumentsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/$documentId': {
      id: '/_authenticated/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof AuthenticatedDocumentsDocumentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/detail/$taskTypeId': {
      id: '/_authenticated/templates/detail/$taskTypeId'
      path: '/templates/detail/$taskTypeId'
      fullPath: '/templates/detail/$taskTypeId'
      preLoaderRoute: typeof AuthenticatedTemplatesDetailTaskTypeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/edit/$documentId': {
      id: '/_authenticated/documents/edit/$documentId'
      path: '/documents/edit/$documentId'
      fullPath: '/documents/edit/$documentId'
      preLoaderRoute: typeof AuthenticatedDocumentsEditDocumentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsPasswordRoute: typeof AuthenticatedSettingsPasswordRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsPasswordRoute: AuthenticatedSettingsPasswordRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRoute
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedGanttRoute: typeof AuthenticatedGanttRoute
  AuthenticatedGanttNewRoute: typeof AuthenticatedGanttNewRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedMyTasksRoute: typeof AuthenticatedMyTasksRoute
  AuthenticatedProjectOverviewRoute: typeof AuthenticatedProjectOverviewRoute
  AuthenticatedSendNoticeRoute: typeof AuthenticatedSendNoticeRoute
  AuthenticatedSimpleCacheTestRoute: typeof AuthenticatedSimpleCacheTestRoute
  AuthenticatedTaskGraphRoute: typeof AuthenticatedTaskGraphRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDocumentsDocumentIdRoute: typeof AuthenticatedDocumentsDocumentIdRoute
  AuthenticatedDocumentsCreateRoute: typeof AuthenticatedDocumentsCreateRoute
  AuthenticatedInstanceCreateRoute: typeof AuthenticatedInstanceCreateRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedStatusManagerRoute: typeof AuthenticatedStatusManagerRoute
  AuthenticatedTasksTaskIdRoute: typeof AuthenticatedTasksTaskIdRoute
  AuthenticatedTasksCreateRoute: typeof AuthenticatedTasksCreateRoute
  AuthenticatedTemplatesManagementRoute: typeof AuthenticatedTemplatesManagementRoute
  AuthenticatedTemplatesSelectRoute: typeof AuthenticatedTemplatesSelectRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedDocumentsIndexRoute: typeof AuthenticatedDocumentsIndexRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedDocumentsEditDocumentIdRoute: typeof AuthenticatedDocumentsEditDocumentIdRoute
  AuthenticatedTemplatesDetailTaskTypeIdRoute: typeof AuthenticatedTemplatesDetailTaskTypeIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRouteRoute: AuthenticatedDashboardRouteRoute,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedGanttRoute: AuthenticatedGanttRoute,
  AuthenticatedGanttNewRoute: AuthenticatedGanttNewRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRoute,
  AuthenticatedMyTasksRoute: AuthenticatedMyTasksRoute,
  AuthenticatedProjectOverviewRoute: AuthenticatedProjectOverviewRoute,
  AuthenticatedSendNoticeRoute: AuthenticatedSendNoticeRoute,
  AuthenticatedSimpleCacheTestRoute: AuthenticatedSimpleCacheTestRoute,
  AuthenticatedTaskGraphRoute: AuthenticatedTaskGraphRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDocumentsDocumentIdRoute: AuthenticatedDocumentsDocumentIdRoute,
  AuthenticatedDocumentsCreateRoute: AuthenticatedDocumentsCreateRoute,
  AuthenticatedInstanceCreateRoute: AuthenticatedInstanceCreateRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedStatusManagerRoute: AuthenticatedStatusManagerRoute,
  AuthenticatedTasksTaskIdRoute: AuthenticatedTasksTaskIdRoute,
  AuthenticatedTasksCreateRoute: AuthenticatedTasksCreateRoute,
  AuthenticatedTemplatesManagementRoute: AuthenticatedTemplatesManagementRoute,
  AuthenticatedTemplatesSelectRoute: AuthenticatedTemplatesSelectRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedDocumentsIndexRoute: AuthenticatedDocumentsIndexRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedDocumentsEditDocumentIdRoute:
    AuthenticatedDocumentsEditDocumentIdRoute,
  AuthenticatedTemplatesDetailTaskTypeIdRoute:
    AuthenticatedTemplatesDetailTaskTypeIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
